version: "3"

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./storage/logs:/var/log/laravel
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana-enterprise:12.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
